server:
  port: 0
  
info:
  app:
    name: product-service SpringBoot application (actuator information)
    description: This is the product service, wrapped in a SpringBoot application
    version: 1.0.0

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    gr.unisystems: INFO